project:
  type: website
  output-dir: docs
title: "The Acute Website"
website:
  sidebar:
    pinned: true
    style: "docked"
    search: true
    contents:
      - index.qmd
      - about.qmd
      - Workpackage_1a.qmd
      - Workpackage_1b.qmd
      - Workpackage_2.qmd
      - Summary.qmd
      - Presentations.qmd
      - Publications.qmd
      - Protocols.qmd
      - Documentation.qmd
format: 
  html:
    theme: cerulean
    css: styles.css
    toc: true

editor: visual

