project:
  type: website
  output-dir: docs
title: "The Acute Project Website"
website:
  sidebar:
    pinned: true
    style: "docked"
    search: true
    contents:
      - index.qmd
      - about.qmd
      - Workpackage_1.qmd
      - Workpackage_2.qmd
      - Presentations.qmd
      - Publications.qmd
      - Protocols.qmd
      - Documentation.qmd
format: 
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

