project:
  type: website
  output-dir: docs

website:
  title: "THE ACUTE PROJECT"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Workpackage_1.qmd
      - Workpackage_2.qmd
      - Presentations.qmd
      - Publications.qmd
      - Protocols.qmd
      - Documentation.qmd
      

format: 
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

