project:
  type: website
  output-dir: docs
title: "The Acute Website"
website:
  sidebar:
    pinned: true
    style: "docked"
    search: true
    contents:
      - Index.qmd
      - About.qmd
      - Workpackage1_singledrug.qmd
      - Workpackage1_combination.qmd
      - Workpackage2.qmd
      - Timeline.qmd
      - Summary.qmd
      - Presentations.qmd
      - Publications.qmd
      - Protocols.qmd
      - Documentation.qmd
format: 
  html:
    theme: flatly
    css: styles.css
    toc: true
editor: visual

